export default {
  namespaced: true,
  state: {
    fetchInvoices: [
      {
        id: 1,
        data: '14-05-2021 01:12',
        score: {
          token: 'BTC',
          title: 'ASDFGDBTC',
        },
        type: 'Перевод',
        yield: 0,
        expenses: 123634.00,
        commission: 14.40,
        status: 'Отменено',
      },
      {
        id: 2,
        data: '20-03-2021 10:31',
        score: {
          token: 'USD',
          title: 'LQMKSDUSD',
        },
        type: 'Пополнение',
        yield: 88020.00,
        expenses: 0,
        commission: 9.53,
        status: 'В процессе',
      },
      {
        id: 3,
        data: '14-05-2021 01:12',
        score: {
          token: 'RUB',
          title: 'EXVKP3RUB',
        },
        type: 'Пополнение',
        yield: 124598.00,
        expenses: 0,
        commission: 318.08,
        status: 'Проведено',
      },
      {
        id: 4,
        data: '02-04-2021 00:54',
        score: {
          token: 'USD',
          title: 'LQMKSDUSD',
        },
        type: 'Вывод',
        yield: 0,
        expenses: 6224.38,
        commission: 0,
        status: 'Проведено',
      },
      {
        id: 5,
        data: '28-03-2021 00:51',
        score: {
          token: 'BTC',
          title: 'ASDFGDBTC',
        },
        type: 'Перевод',
        yield: 0,
        expenses: 123634.00,
        commission: 21.48,
        status: 'Проведено',
      },
      {
        id: 6,
        data: '20-03-2021 10:31',
        score: {
          token: 'USD',
          title: 'LQMKSDUSD',
        },
        type: 'Пополнение',
        yield: 88020.00,
        expenses: 0,
        commission: 9.92,
        status: 'Проведено',
      },
      {
        id: 7,
        data: '14-05-2021 01:12',
        score: {
          token: 'RUB',
          title: 'EXVKP3RUB',
        },
        type: 'Пополнение',
        yield: 124598.00,
        expenses: 0,
        commission: 198.00,
        status: 'Проведено',
      },
      {
        id: 8,
        data: '02-04-2021 00:54',
        score: {
          token: 'USD',
          title: 'LQMKSDUSD',
        },
        type: 'Вывод',
        yield: 0,
        expenses: 23134.38,
        commission: 24.38,
        status: 'Проведено',
      },
      {
        id: 9,
        data: '28-03-2021 00:51',
        score: {
          token: 'BTC',
          title: 'ASDFGDBTC',
        },
        type: 'Перевод',
        yield: 0,
        expenses: 123634.00,
        commission: 34.03,
        status: 'Проведено',
      },
      {
        id: 10,
        data: '20-03-2021 10:31',
        score: {
          token: 'USD',
          title: 'LQMKSDUSD',
        },
        type: 'Пополнение',
        yield: 88020.00,
        expenses: 0,
        commission: 21.80,
        status: 'Проведено',
      },
      {
        id: 11,
        data: '14-05-2021 01:12',
        score: {
          token: 'BTC',
          title: 'ASDFGDBTC',
        },
        type: 'Перевод',
        yield: 0,
        expenses: 123634.00,
        commission: 14.40,
        status: 'Отменено',
      },
      {
        id: 12,
        data: '20-03-2021 10:31',
        score: {
          token: 'USD',
          title: 'LQMKSDUSD',
        },
        type: 'Пополнение',
        yield: 88020.00,
        expenses: 0,
        commission: 9.53,
        status: ' В процессе',
      },
      {
        id: 13,
        data: '14-05-2021 01:12',
        score: {
          token: 'RUB',
          title: 'EXVKP3RUB',
        },
        type: 'Пополнение',
        yield: 124598.00,
        expenses: 0,
        commission: 318.08,
        status: 'Проведено',
      },
      {
        id: 14,
        data: '02-04-2021 00:54',
        score: {
          token: 'USD',
          title: 'LQMKSDUSD',
        },
        type: 'Вывод',
        yield: 0,
        expenses: 6224.38,
        commission: 0,
        status: 'Проведено',
      },
      {
        id: 15,
        data: '28-03-2021 00:51',
        score: {
          token: 'BTC',
          title: 'ASDFGDBTC',
        },
        type: 'Перевод',
        yield: 0,
        expenses: 123634.00,
        commission: 21.48,
        status: 'Проведено',
      },
      {
        id: 16,
        data: '20-03-2021 10:31',
        score: {
          token: 'USD',
          title: 'LQMKSDUSD',
        },
        type: 'Пополнение',
        yield: 88020.00,
        expenses: 0,
        commission: 9.92,
        status: 'Проведено',
      },
      {
        id: 17,
        data: '14-05-2021 01:12',
        score: {
          token: 'RUB',
          title: 'EXVKP3RUB',
        },
        type: 'Пополнение',
        yield: 124598.00,
        expenses: 0,
        commission: 198.00,
        status: 'Проведено',
      },
      {
        id: 18,
        data: '02-04-2021 00:54',
        score: {
          token: 'USD',
          title: 'LQMKSDUSD',
        },
        type: 'Вывод',
        yield: 0,
        expenses: 23134.38,
        commission: 24.38,
        status: 'Проведено',
      },
      {
        id: 19,
        data: '28-03-2021 00:51',
        score: {
          token: 'BTC',
          title: 'ASDFGDBTC',
        },
        type: 'Перевод',
        yield: 0,
        expenses: 123634.00,
        commission: 34.03,
        status: 'Проведено',
      },
      {
        id: 20,
        data: '20-03-2021 10:31',
        score: {
          token: 'USD',
          title: 'LQMKSDUSD',
        },
        type: 'Пополнение',
        yield: 88020.00,
        expenses: 0,
        commission: 21.80,
        status: 'Проведено',
      },
    ],
    pagination: { perPage: 10, currentPage: 1 },

  },
  getters: {

  },
  actions: {},
  mutations: {
    paginations(state, payload) {
      state.pagination = payload
    },
  },
}
